import GoogleAnalytics from "@/app/components/GoogleAnalytics";
import "./globals.css";
import type { Metadata } from "next";
import { Vazirmatn } from "next/font/google";
import CookieBanner from "@/app/components/CookieBanner";
import Header from "./components/Header";

const vazirmatn = Vazirmatn({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "JOJOFIT",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="fa">
      <GoogleAnalytics GA_MEASUREMENT_ID="G-6VF8BJ01X5" />
      <body
        className={`${vazirmatn.className} transition duration-100  bg-neutral-100 dark:bg-neutral-900 min-h-screen max-w-screen-md mx-auto `}
      >
        <Header />
        <main className={` overflow-x-hidden relative z-30 px-6`}>
          {children}
        </main>
        <CookieBanner />
      </body>
    </html>
  );
}
